# Day 30: Working with Exception Handling and JSON

## Reflection  
  Today, I continued my journey in the 100 Days of Python challenge by completing Day 30. It was an informative and productive day where I delved deeper into the following concepts:

  1. **Exception Handling in Python**: I revisited the concept of handling errors using try-except blocks and discovered the usefulness of the else statement, which executes if no exceptions occur.
  2. **Raising Own Exception**: I learned how to create and raise custom exceptions to handle specific scenarios in my code effectively.
  3. 

  I also managed to complete 2 exercises, add error handling on my [NATO Alphabet](https://github.com/johnivanpuayap/NatoAlphabet) project and was able to improve my [Password Manager](https://github.com/johnivanpuayap/PasswordManager) App by changing data.txt to a JSON, adding exception handling, adding a search website feature and also adding messageboxes.

  I was able to learn a lot today! I am actually excited that I took a look for next days project which is a Flash Card App Capstone Project. 70 Days to go 

## Progress
 - Completed Day 30 of 100 Days of Python